Proximity/force-app/main/default/objects/Case_Triggers__c/Case_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Enable or Disable case triggers</description>
    <label>Case Triggers</label>
</CustomObject>

Proximity/force-app/main/default/objects/Case_Triggers__c/fields/Create_Task_for_new_Case__c.field-meta.xml
<CustomField>
    <fullName>Create_Task_for_new_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If ticked then each time a new Case is created, a new Task will be created also</description>
    <inlineHelpText>Create a new Task on Case Creation</inlineHelpText>
    <label>Create Task for new Case</label>
    <type>Checkbox</type>
</CustomField>

Proximity/force-app/main/default/classes/CaseTriggerHandler.cls
public with sharing class CaseTriggerHandler {
    public Case_Triggers__c settings = Case_Triggers__c.getOrgDefaults();
    public CaseTriggerHandler(List<Case> newCases, Map<Id, Case> oldMap) {
        if ( Trigger.isBefore ) {
            if ( Trigger.isInsert ) {

            } else if ( Trigger.isUpdate ) {

            }else if ( Trigger.isDelete ) {
                
            }
        } else {
            if ( Trigger.isInsert ) {
                createTask(newCases);
            } else if ( Trigger.isUpdate ) {

            }else if ( Trigger.isDelete ) {
                
            }else if ( Trigger.isUndelete ) {
                
            }
        }
    }

    private void createTask(List<Case> newCases) {
        if ( settings.Create_Task_for_new_Case__c ) {
            List<Task> newTasks = new List<Task>();
            for ( Case thisCase : newCases ) {
                Task newTask = new Task(OwnerId = thisCase.OwnerId,
                                        Status = 'Not Started',
                                        Subject = 'Welcome call for '+thisCase.CaseNumber,
                                        Priority = 'Normal');
                if ( thisCase.Priority == 'High' ) {
                    newTask.ActivityDate = Date.today().addDays(7);
                } else if ( thisCase.Priority == 'Medium' ) {
                    newTask.ActivityDate = Date.today().addDays(14);
                } else {
                    newTask.ActivityDate = Date.today().addDays(21);
                }
                newTasks.add(newTask);
            }

            if ( newTasks.size() > 0 ) {
                try{
                    insert newTasks;
                } catch (Exception e) {
                    System.debug('One or more Tasks failed to create because the following error occured '+e.getMessage()+' on line '+e.getLineNumber());
                    //Ideally we would have an object where we can store details of any errors thrown, so we know when and if a problem happens, but this is not in scope
                }
            }
        }
    }
}